сделаны минимальные требование по заданию
stepancar-web-programming/2023-fall-lab-portfolio-istamov-u.-y.-u. pull request #4
Opened 2024-01-07 01:59 UTC by ulaista

добавлено вторая страница blog, 
добавлены видео к странице (пока не официальные) из youtube, 
добавлены стили
закрыт старый не правильный PR - сделано новое по dev к main

2024-01-07 05:45 UTC, stepancar commented on public/blog.html
> +  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
ниже вы полключаете bootstrap из cdn,  тут он точно нужен?

2024-01-07 05:46 UTC, stepancar commented on public/blog.html
> +    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
этот файл вы подключаете ниже, из cdn, разве нет?

2024-01-07 06:02 UTC, stepancar commented on public/blog.html
> +    <footer id="footer">
Давайте подумаем как можно сделать ваш сайт таким образом при котором вам не потребуется поддерживать идентичность в двух файлах

2024-01-07 06:03 UTC, stepancar commented on public/assets/vendor/php-email-form/validate.js
> +  let forms = document.querySelectorAll('.php-email-form');
Не вижу в этом проекте eslint которым вы проверяете ваш код на соответствие гайдлайнам

2024-01-07 06:04 UTC, stepancar requested changes
Оставил комментарии

2024-01-11 17:40 UTC, ulaista commented on public/blog.html
> +  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
локальный bootstrap и остальные библиотеки убрал, добавил через cdn, оказывается так быстрее, протестировал через другой репозиторий [ulaista.github.io](url) , там видно коммиты как я пробывал сначала загрузить сайт через локальные библиотеки, и через cdn

2024-01-11 17:41 UTC, ulaista commented on public/blog.html
> +    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
точно тоже история как со стилями - 
локальный bootstrap и остальные библиотеки убрал, добавил через cdn, оказывается так быстрее, протестировал через другой репозиторий [ulaista.github.io](url) , там видно коммиты как я пробывал сначала загрузить сайт через локальные библиотеки, и через cdn

2024-01-11 17:46 UTC, ulaista commented on public/blog.html
> +    <footer id="footer">
повторяющийся часть footer и ссылки на стили и на скрипты убрал, и через partials.js через функию connectedCallback - > innerHTML добавил в html файлы при загрузке, тем самым убрав повтор. 
Сами функции в partials.js обернул на IIFE для того чтобы не возникало конфликт при исполнении

2024-01-11 17:48 UTC, ulaista commented on public/assets/vendor/php-email-form/validate.js
> +  let forms = document.querySelectorAll('.php-email-form');
убрал этот так как оно подгрузился с библиотеками в проекте роль не играет, в изначальном коммите случайно запушил

2024-01-16 07:48 UTC, stepancar commented on public/partials.js
> +    customElements.define('section-footer', SectionFooter)
Элегантно! Предлагаю обсудить это на экзамене

2024-01-16 07:49 UTC, stepancar approved these changes

2024-01-16 07:50 UTC, merged

2024-01-16 08:31 UTC, ulaista commented on public/partials.js
> +    customElements.define('section-footer', SectionFooter)
Спасибо )